name: Deploy to prod
on:
  workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      cluster: prod-gcp
      ingress: https://workinnorway.nav.no
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}